# Generated by Django 5.1.4 on 2025-01-04 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0002_remove_user_birth_remove_user_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='UserProfileDD',
        ),
    ]
