# Generated by Django 5.1.4 on 2025-01-05 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userManagement', '0004_delete_user_delete_userprofiledd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('major', models.JSONField()),
                ('bio', models.TextField()),
                ('preferences', models.TextField()),
                ('ethnicity', models.ManyToManyField(to='userManagement.ethnicity')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManagement.faculty')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManagement.grade')),
            ],
        ),
    ]
