# Generated by Django 5.1.4 on 2025-01-05 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ethnicity',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='grade',
        ),
        migrations.DeleteModel(
            name='Ethnicity',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
