version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - weaviate
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/mcgill_dating
      - WEAVIATE_URL=http://weaviate:8080

  ml:
    build:
      context: .
      dockerfile: docker/Dockerfile.ml
    depends_on:
      - weaviate
    environment:
      - WEAVIATE_URL=http://weaviate:8080

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  weaviate:
    image: semitechnologies/weaviate:1.24.1
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
    volumes:
      - weaviate_data:/var/lib/weaviate

volumes:
  mongodb_data:
  weaviate_data:
