# Generated by Django 4.2.7 on 2024-12-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseInteraction', '0002_userprofile_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(default='10/10/10'),
        ),
    ]
