# Generated by Django 4.2.7 on 2024-12-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseInteraction', '0003_alter_user_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
