# Generated by Django 4.2.7 on 2024-12-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseInteraction', '0004_alter_user_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=50),
        ),
    ]
