# Generated by Django 3.1.12 on 2024-12-31 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseInteraction', '0005_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
